### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by parthk2510** [andreyglauzer/VigilantOnion#12]
Receiving this error while running  requirement.txt 
pip==21.3.1  (new version is also giving the same problem )

![Screenshot from 2022-07-07 20-20-53](https://user-images.githubusercontent.com/87540263/177740416-f2202e69-dde0-4468-8027-1c03a21eb675.png)

**Comment by ramixix** [comment]
That is because BeautifulSoup library, I was getting the same error so I just edit the requirments.txt and change the beautifulsoup to beautifulsoup4
