### ISSUE TITLE
[enhancement] I would suggest using elasticsearch than mysql Db

### ISSUE THREAD

**Issue by danieleperera** [andreyglauzer/VigilantOnion#2]
I really like the idea of building a django app to collect and crawl tor hidden services, however, in my opinion, using a SQL Db is a limit. I would suggest using sqlite3 for the django app and using elasticsearch to index crawled hidden sites.

I forked your project I'll try to make the above improvements. Keep up the good work.

**Comment by andreyglauzer** [comment]
When I write I didn't know much about ELK. Today I already know a lot, this project was stopped for a long time, but I developed it again, I believe that soon I will create an integration with ELK or neo4j.

Feel free to develop and accustom the project.

**Comment by danieleperera** [comment]
Hey andrey, 

I've created this repo. https://github.com/danieleperera/OnionIngestor
And I'm using your engine scripts to collect and find onion links from clearnet. Do you mind checking it out?
I think we could do a collab.

**Comment by andreyglauzer** [comment]
Hey Daniele,

Your work is incredible, I really liked the method used.
I believe that we can do a project together.
